### ISSUE TITLE
Support publishing heartbeat messages

### ISSUE THREAD

**Issue by ripienaar** [choria-io/stream-replicator#83]
When there's constant data monitoring SR is easy, but for idle streams or where messages come and go it's quite hard.

SR should support publishing heartbeat messages into a list of subjects, each subject should:

 * Have a timestamp body
 * Have an originator host header `Choria-SR-Originator`
 * Have a published subject header `Choria-SR-Subject`
 * Support arbitrary headers 

The publisher should be leadership aware

Sample configuration might be like this, it would go in the existing config file:

```
heartbeats:
  leader_election: true
  interval: 10s
  url: "nats://x.com:4222,nats://y.com:4222"
  tls: {} # connection properties that applies to all publishers
  choria: {} # connection properties that applies to all publishers
  headers:
     X: Y

  subjects:
     - subject: s.1:
       interval: 20s # overrides
       headers:      # merges
          Y: Z.           
     - subject: s.2   # defaults to 10s and X:Y headers
```

This would spawn a single go routine per subject that just publish this stuff all the time on the frequency. It needs to use a JetStream publish and log on ack failures.

The election name would derive from the main `ReplicatorName` in the configuration and be something like `{{ReplicatorName}}_HB`.  All publishers would share the same active/paused boolean managed by Leader Election.

We need to keep at least these prom stats:

 * `hb_subjects` number of subjects being published in the hb system with labels `replicator` and `subject`
 * `hb_published_ctr` with labels `replicator` and `subject`
 * `hb_publish_error_ctr` with labels `replicator` and `subject`
 * `hb_publish_time` indicating time taken to publish a message with labels `replicator` and `subject`
 * `hb_paused` indicating if its paused under leader election or not with labels `replicator`
